---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  config.toml: |
    [kubemonkey]
    run_hour = {{ .Values.kubemonkey.run_hour }}
    start_hour = {{ .Values.kubemonkey.start_hour }}
    end_hour = {{ .Values.kubemonkey.end_hour }}
    blacklisted_namespaces = ["{{ .Values.kubemonkey.blacklisted_namespaces }}"]
    whitelisted_namespaces = ["{{ .Values.kubemonkey.whitelisted_namespaces }}"]
    time_zone = "{{ .Values.kubemonkey.time_zone }}"
    graceperiod_sec= {{ .Values.kubemonkey.graceperiod_sec }}
    [debug]
    enabled= {{ .Values.kubemonkey.debug.enabled }}
    schedule_immediate_kill= {{ .Values.kubemonkey.debug.schedule_immediate_kill }}
