# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.define "docker-build" do |node|
      node.vm.hostname = "docker-build"
      node.vm.network :private_network, ip: "10.100.198.200"
      node.vm.provision :shell, inline: "sudo apt update"
      node.vm.provision :shell, inline: "sudo apt -y install apt-transport-https ca-certificates curl software-properties-common"
      node.vm.provision :shell, inline: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      node.vm.provision :shell, inline: "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""
      node.vm.provision :shell, inline: "sudo apt update"
      node.vm.provision :shell, inline: "sudo apt install -y docker-ce"
      node.vm.provision :shell, inline: "sudo apt install -y default-jre"
    end
end