{
 "title": "The DevOps Toolkit: Kubernetes (via Prometheus)",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "secBucket",
    "label": "Requests seconds bucket",
    "query": "\"10\",\"5\",\"2.5\",\"1\",\"0.5\",\"0.25\",\"0.1\",\"0.05\",\"0.025\",\"0.01\",\"0.005\""
   },
   { "name": "podAgeDays", "label": "Max Pod age in days", "query": "${VAR_PODAGEDAYS}" },
   { "name": "minBytes", "label": "Minimum Bytes", "query": "${VAR_MINBYTES}" },
   { "name": "minCpu", "label": "Minimum CPU", "query": "${VAR_MINCPU}" },
   { "name": "reqPercent", "label": "Requests bucket %", "query": "${VAR_REQPERCENT}" },
   { "name": "reqPerSec", "label": "Requests per second", "query": "${VAR_REQPERSEC}" },
   { "name": "errorPercent", "label": "Error percentage", "query": "${VAR_ERRORPERCENT}" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "The total number of nodes",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Unschedulable Pods",
   "type": "singlestat",
   "description": "The number of Pods in failed, unknown, or pending state",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Unknown|Pending\"})"
    }
   ]
  },
  {
   "title": "Pods older than $podAgeDays days",
   "type": "singlestat",
   "description": "The number of Pods older than $podAgeDays days",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((time() - kube_pod_start_time{namespace!=\"kube-system\"}) > bool (60 * 60 * 24 * $podAgeDays))"
    }
   ]
  },
  {
   "title": "Ingresses with requests in $secBucket bucket below $reqPercent%",
   "type": "singlestat",
   "description": "The number of nginx Ingress resources with less than $reqPercent% of requests in $secBucket seconds bucket.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by(ingress) (rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"$secBucket\"}[5m])) / sum by(ingress) (rate(nginx_ingress_controller_request_duration_seconds_count[5m])) < bool ($reqPercent / 100))"
    }
   ]
  },
  {
   "title": "Ingresses with average of over $reqPerSec req per sec",
   "type": "singlestat",
   "description": "Calculates the number of nginx Ingresses with more than $reqPerSec requests per second over 5 minutes interval divided by Deployment replicas.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by(ingress) (rate(nginx_ingress_controller_requests[5m])) / sum by(ingress) (label_join(kube_deployment_status_replicas, \"ingress\", \",\", \"deployment\")) > bool $reqPerSec)"
    }
   ]
  },
  {
   "title": "Ingresses with over $errorPercent% of 5xx responses",
   "type": "singlestat",
   "description": "The percentage of nginx Ingresses with more than $errorPercent% of responses with 5xx code.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests[5m])) by (ingress) > bool ($errorPercent / 100))"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Nodes",
   "type": "table",
   "description": "The nodes of the cluster",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(kube_node_info) by (node, kubelet_version)"
    }
   ]
  },
  {
   "title": "Unschedulable Pods",
   "type": "table",
   "description": "Pods that could not be scheduled",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Unknown|Pending\"}) by (namespace, pod) > 0"
    }
   ]
  },
  {
   "title": "Pods older than $podAgeDays days",
   "type": "table",
   "description": "The number of Pods older than $podAgeDays days",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum((time() - kube_pod_start_time{namespace!=\"kube-system\"}) > (60 * 60 * 24 * $podAgeDays)) by (namespace, pod)"
    }
   ]
  },
  {
   "title": "% of Ingress requests in ${secBucket}s bucket",
   "type": "graph",
   "description": "Calculates the percentage of requests in $$secBucket bucket entering through nginx Ingress.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "  sum by(ingress) (rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"$secBucket\"}[5m])) / sum by(ingress) (rate(nginx_ingress_controller_request_duration_seconds_count[5m]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress requests per second by Deployment  replicas",
   "type": "graph",
   "description": "Calculates the number of Ingress requests divided by Deployment replicas.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(ingress) (rate(nginx_ingress_controller_requests[5m])) / sum by(ingress) (label_join(kube_deployment_status_replicas, \"ingress\", \",\", \"deployment\"))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "% of 5xx responses",
   "type": "graph",
   "description": "The percentage of nginx Ingress responses with 5xx code.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests[5m])) by (ingress) > 0",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "% of actual memory vs the limit",
   "type": "graph",
   "description": "The percentage of memory usage compared to the limit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_join(container_memory_usage_bytes{namespace!=\"kube-system\", container_name!=\"\"}, \"pod\", \",\", \"pod_name\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace!=\"kube-system\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "% of actual vs reserved memory",
   "type": "graph",
   "description": "The percentage actual memory usage compared to reserved. The calculation excludes Pods with reserved memory equal to or smaller than $minBytes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_join(container_memory_usage_bytes{namespace!=\"kube-system\", namespace!=\"ingress-nginx\", container_name!=\"\"}, \"pod\", \",\", \"pod_name\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace!=\"kube-system\"}) by (pod) and sum(kube_pod_container_resource_requests_memory_bytes{namespace!=\"kube-system\"}) by (pod) > $minBytes",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "% of actual vs reserved CPU",
   "type": "graph",
   "description": "The percentage actual CPU usage compared to reserved. The calculation excludes Pods with reserved CPU equal to or smaller than $minCpu.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_join(rate(container_cpu_usage_seconds_total{namespace!=\"kube-system\", pod_name!=\"\"}[5m]), \"pod\", \",\", \"pod_name\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace!=\"kube-system\", namespace!=\"ingress-nginx\"}) by (pod) and sum(kube_pod_container_resource_requests_cpu_cores{namespace!=\"kube-system\", namespace!=\"ingress-nginx\"}) by (pod) > $minCpu",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}