replicaCount: 3
image:
  tag: latest
ingress:
  enabled: false
service:
  type: NodePort
rbac:
  enabled: true
resources:
  limits:
   cpu: 0.2
   memory: 20Mi
  requests:
   cpu: 0.1
   memory: 10Mi
namespace: "kube-system"
name: "kube-monkey"
#refer to https://github.com/asobti/kube-monkey for details about below attributes
kubemonkey:
  run_hour: 10
  start_hour: 11
  end_hour: 14
  blacklisted_namespaces: "kube-system" #multiples can be declared ex : "xxx","yyy"
  whitelisted_namespaces: "go-demo-5" #multiples can be declared ex : "xxx","yyy"
  time_zone: "Australia/Melbourne"
  graceperiod_sec: 10
  debug:
   enabled: true
   schedule_immediate_kill: true
