---
# Source: istio-init/templates/job-crd-11.yaml
apiVersion: batch/v1
kind: Job
metadata:
  namespace: istio-system
  name: istio-init-crd-11-1.3.0
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
      - name: istio-init-crd-11
        image: "docker.io/istio/kubectl:1.3.0"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: crd-11
          mountPath: /etc/istio/crd-11
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/istio/crd-11/crd-11.yaml"]
      volumes:
      - name: crd-11
        configMap:
          name: istio-crd-11
      restartPolicy: OnFailure
