apiVersion: v1
kind: Namespace
metadata:
  name: go-demo-3

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: go-demo-3
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: api
          servicePort: 8080

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
  namespace: go-demo-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: go-demo-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mongo:3.3
        resources:
          limits:
            memory: "100Mi"
            cpu: 0.1
          requests:
            memory: "50Mi"
            cpu: 0.01
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: go-demo-3
spec:
  ports:
  - port: 27017
  selector:
    app: db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: go-demo-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-3
        env:
        - name: DB
          value: db
        readinessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
        resources:
          limits:
            memory: "25Mi"
            cpu: 0.1  
          requests:
            memory: "10Mi"
            cpu: 0.01

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: go-demo-3
spec:
  ports:
  - port: 8080
  selector:
    app: api
